---
# tasks file for ansible_systemd_unicorn
- name: Unicorn | Copy systemd template to systemd multiuser directory
  template:
    src: unicorn_systemd
    dest: '/lib/systemd/system/unicorn.service'
    owner: root
    group: root
  become: yes
- name: Configure Unicorn to Start on Reboot and Start the Process
  systemd:
    name: unicorn
    daemon_reload: yes
    enabled: yes
    state: started
  become: yes
