---
# tasks file for ansible_systemd_unicorn
- name: Unicorn | Copy systemd template to systemd multiuser directory
  template: src=unicorn_systemd dest=/lib/systemd/system/unicorn.service owner=root group=root
  sudo: yes
- command: systemctl daemon-reload
  sudo: yes
- command: systemctl enable unicorn
  becomes: yes
- command: systemctl start unicorn
  sudo: yes
