---
# tasks file for ansible_systemd_unicorn
- name: Unicorn | Copy systemd template to systemd multiuser directory
  template: src=unicorn_systemd dest=/lib/systemd/system/unicorn.service owner=root group=root
  becomes: yes
- name: reload the systemd process after modifying config file
  command: systemctl daemon-reload
  becomes: yes
- name: configure unicorn to restart on reboot
  command: systemctl enable unicorn
  becomes: yes
- name: explicitly start unicorn
  command: systemctl start unicorn
  becomes: yes
